name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Eğer ana dalınızın adı 'master' ise burayı düzeltin
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
    - name: Build project
        run: npm run build
      
      - name: Create .nojekyll
        run: touch ./dist/.nojekyll  # <--- BU 2 SATIRI EKLEYİN
      
      - name: Upload artifact
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Vite varsayılan olarak 'dist' klasörüne çıktı verir

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
